### PR TITLE
Analytics test setup

### PR DESCRIPTION
**Pull request by VathsalaAchar**
Setting up to run flask tests required quite a few changes:
- using application factory pattern 
- setting up development and test configurations
- flask blueprints to register views to the app
- changes to how we connect to mongo db in flask - using flask_pymongo now
- mongo db service to run during build pipeline

Sources:
[MongoDB GitHub Actions setup](https://stackoverflow.com/questions/66317184/github-actions-cannot-connect-to-mongodb-service)
[Flask Application factory pattern](https://flask.palletsprojects.com/en/3.0.x/tutorial/factory/#run-the-application)
[Flask Blueprints](https://flask.palletsprojects.com/en/3.0.x/blueprints/)
[Using config for test set up](https://stackoverflow.com/questions/56029111/how-do-i-mock-pymongo-for-testing-with-a-flask-app)

### CODE REVIEW

**Comment by VathsalaAchar** [comment]
I've also created some test data at `analytics/tests/db_init_data.json` and updated the unit tests for analytics service to use this data via fixtures. 

There was a failure on the build pipeline due to `pytest` running in the parent folder instead of in `analytics`. It's been fixed and all checks have passed.

We currently have 7 unit tests for analytics.

**Review by HarshiSharma — COMMENTED** [review]
Look good, but it has conflict that need resolving

**Comment by VathsalaAchar** [comment]
I've rebased against main and fixed conflicts.

**Review by Ahuja-Nisha — COMMENTED** [review]
good one

**Comment by Ahuja-Nisha** [comment]
ok

**Comment by Ahuja-Nisha** [comment]
done

**Review by Ahuja-Nisha — COMMENTED** [review]
Approved

**Review by Ahuja-Nisha — APPROVED** [review]
Approved

**Pull request merged**
