### PR TITLE
adding changes for junit and mockito tests

### PR DESCRIPTION
**Pull request by Ahuja-Nisha**
plz check

### CODE REVIEW

**Comment by VathsalaAchar** [comment]
Great work on the PR @Ahuja-Nisha 
Could you put in a note about how to run the tests so I can check this locally and then review?

**Comment by VathsalaAchar** [comment]
I've checked these tests and the report says the tests are passing

Screenshot 2024-04-08 at 13 50 51 (2)

Could you confirm this @Ahuja-Nisha ?

**Comment by VathsalaAchar** [comment]
I've also rebased from main to keep this branch updated.

**Comment by LakshmiAvanthiKaneti** [comment]
Hi @Ahuja-Nisha can you please explain the steps to run the tests

**Comment by VathsalaAchar** [comment]
> Hi @Ahuja-Nisha can you please explain the steps to run the tests

This is [what I used ](https://courses.cs.washington.edu/courses/cse331/19wi/docs/tools/test-reports.html#:~:text=Gradle%20generates%20a%20Test%20Report,Gradle%20task%20from%20your%20IDE.&text=A%20failing%20build%20has%20the,bottom%20of%20the%20second%20output.)

**Review by VathsalaAchar — APPROVED** [review]

**Comment by LakshmiAvanthiKaneti** [comment]
I checked the tests and tests was running successfully

**Review by LakshmiAvanthiKaneti — APPROVED** [review]
Nice work @Ahuja-Nisha I did run the tests in the code space and tests are running fine.

**Pull request merged**
